-- tmux navigation keymaps
vim.keymap.set("n", "<c-h>", "<cmd>TmuxNavigateLeft<cr>", { desc = "Navigate left" })
vim.keymap.set("n", "<c-j>", "<cmd>TmuxNavigateDown<cr>", { desc = "Navigate down" })
vim.keymap.set("n", "<c-k>", "<cmd>TmuxNavigateUp<cr>", { desc = "Navigate up" })
vim.keymap.set("n", "<c-l>", "<cmd>TmuxNavigateRight<cr>", { desc = "Navigate right" })
vim.keymap.set("n", "<c-\\>", "<cmd>TmuxNavigatePrevious<cr>", { desc = "Navigate previous" })

-- Visual mode: exit visual mode then navigate
vim.keymap.set("v", "<c-h>", "<Esc><cmd>TmuxNavigateLeft<cr>", { desc = "Navigate left" })
vim.keymap.set("v", "<c-j>", "<Esc><cmd>TmuxNavigateDown<cr>", { desc = "Navigate down" })
vim.keymap.set("v", "<c-k>", "<Esc><cmd>TmuxNavigateUp<cr>", { desc = "Navigate up" })
vim.keymap.set("v", "<c-l>", "<Esc><cmd>TmuxNavigateRight<cr>", { desc = "Navigate right" })
vim.keymap.set("v", "<c-\\>", "<Esc><cmd>TmuxNavigatePrevious<cr>", { desc = "Navigate previous" })

-- Insert mode: exit insert mode then navigate
vim.keymap.set("i", "<c-h>", function()
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-\\><C-n>", true, false, true), "n", false)
  vim.cmd("TmuxNavigateLeft")
end, { desc = "Navigate left" })
vim.keymap.set("i", "<c-j>", function()
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-\\><C-n>", true, false, true), "n", false)
  vim.cmd("TmuxNavigateDown")
end, { desc = "Navigate down" })
vim.keymap.set("i", "<c-k>", function()
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-\\><C-n>", true, false, true), "n", false)
  vim.cmd("TmuxNavigateUp")
end, { desc = "Navigate up" })
vim.keymap.set("i", "<c-l>", function()
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-\\><C-n>", true, false, true), "n", false)
  vim.cmd("TmuxNavigateRight")
end, { desc = "Navigate right" })
vim.keymap.set("i", "<c-\\>", function()
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-\\><C-n>", true, false, true), "n", false)
  vim.cmd("TmuxNavigatePrevious")
end, { desc = "Navigate previous" })
